project:
  type: website
  output-dir: docs

resources:
  - scan-media.html

website:
  title: "SWAPER"
  favicon: logo.png
  search: true
  navbar:
    pinned: true
    left:
      - text: "About"
        icon: house
        href: index.qmd
      - text: "News"
        href: news.qmd
      - text: "Seminars"
        menu: 
          - text: "All seminars"
            href: exp1.qmd
          - text: "Registered"
            href: exp2.qmd
      - text: "Learning"
        menu:
          - text: "Training"
            href: training.qmd
          - text: "Documents"
            href: document.qmd
      - text: "EBS"
        icon: newspaper
        href: scan-media.html
      - text: "IBS"
        icon: database
        href: report.qmd
    right:
      - icon: github
        href: https://github.com/HCDC-GSCB/
      - text: "Chill"
        icon: discord
        href: game.html

  sidebar:
    - id: training
      title: "Training"
      style: "docked"
      contents:
        - section: "Modelling team"
          contents:
            - htgs.qmd
            - threshold.qmd
        - section: "PHEOC team"
          contents:
            - ghs.qmd
            - phem.qmd
            - pheoc.qmd
        - section: "R language"
          contents:
            - intro.qmd
            - r01.qmd
            - r02.qmd
            - r03.qmd
            - r04.qmd
            - exercise1.qmd
            - exercise2.qmd
            - exercise3.qmd

  back-to-top-navigation: true
  page-footer: 
    right: "© 2025 HCDC - SWAPER"

format:
  html:
    respect-user-color-scheme: true
    self-contained: true
    theme:
      light: flatly
      dark: darkly
    toc: true
    css: custom.css
    includes: 
      after-body: loading.html

editor: visual
