project:
  type: website
  output-dir: docs

website:
  title: "SWAPER"
  navbar:
    background: secondary
    search: true
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Seminars"
        menu: 
          - text: "All seminars"
            href: exp1.qmd
          - text: "Registerd"
            href: exp2.qmd
    tools:
      - icon: github
        menu:
          - text: "Source code"
            href: https://github.com/HCDC-GSCB/
    back-to-top-navigation: true
    page-footer: "Copyright 2025, SWAPER"
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

