project:
  type: website
  output-dir: docs

website:
  title: "SWAPER"
  favicon: logo.png
  search: true
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Website is under construction"
    type: primary
    position: above-navbar
  navbar:
    pinned: true
    left:
      - text: "About us"
        href: about/index.qmd
      - text: "News"
        href: news/index.qmd
      - text: "Seminars"
        href: seminars/index.qmd
      - text: "Learning"
        menu:
          - text: "Training"
            href: training/index.qmd
          - text: "Book"
            href: book/index.qmd
      - text: "EBS"
        icon: newspaper
        href: ebs.html
      - text: "Report"
        icon: database
        href: report/index.qmd
    right:
      - icon: github
        href: https://github.com/HCDC-GSCB/
      - text: "Chill"
        icon: discord
        href: game.html

  sidebar:
    - id: training
      title: "Training"
      style: "docked"
      contents:
        - section: "Modelling team"
          contents:
            - training/htgs.qmd
            - training/threshold.qmd
        - section: "PHEOC team"
          contents:
            - training/ghs.qmd
            - training/phem.qmd
            - training/pheoc.qmd
        - section: "R language"
          contents:
            - training/intro.qmd
            - training/r01.qmd
            - training/r02.qmd
            - training/r03.qmd
            - training/r04.qmd
            - training/exercise1.qmd
            - training/exercise2.qmd
            - training/exercise3.qmd

  back-to-top-navigation: true
  page-footer:
    left: |
      📧 Email to: khoagscb@hcdc.gov.vn<br>
      📍 Address: 366A Au Duong Lan Street, Chanh Hung Ward, HCMC
    right: "© 2025 HCDC - SWAPER"

format:
  html:
    respect-user-color-scheme: true
    self-contained: true
    theme:
      light: flatly
      dark: darkly
    toc: true
    css: custom_v2.css
    includes: 
      after-body: loading.html

editor: source