---
title: "Quality of surveillance system"
---

To more information about SWAPER, please click on following link: <https://hcdc-gscb.github.io/swaper/>

## Agenda of Topic {.unnumbered}

+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
|       | Lesson                                                                                                                                                   | Content                                                                                                                                                  |
+=======+==========================================================================================================================================================+==========================================================================================================================================================+
| Day 1 | IBS, EBS and tools for supporting EBS                                                                                                                    | Indicator-based surveillance                                                                                                                             |
|       |                                                                                                                                                          |                                                                                                                                                          |
|       | [🚀 Presentation](https://www.canva.com/design/DAGjL6n95CI/yXaBi-lSYjWxiqhBR0Rpgw/edit?ui=eyJIIjp7IkEiOnRydWV9fQ)                                        | Event-based surveillance                                                                                                                                 |
|       |                                                                                                                                                          |                                                                                                                                                          |
|       |                                                                                                                                                          | Tools for supporting EBS                                                                                                                                 |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Day 2 | Data structures required for BTN monitoring and integrated monitoring systems                                                                            | Data collection requirements in service response                                                                                                         |
|       |                                                                                                                                                          |                                                                                                                                                          |
|       |                                                                                                                                                          | Advantages and disadvantages in monitoring system of ID                                                                                                  |
|       |                                                                                                                                                          |                                                                                                                                                          |
|       |                                                                                                                                                          | Introduction to integrated monitoring system                                                                                                             |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Day 3 | Evaluation of infectious disease surveillance systems                                                                                                    | Research introduction: *Assessment of the current status of infectious disease surveillance system and public health events in Ho Chi Minh City in 2024* |
|       |                                                                                                                                                          |                                                                                                                                                          |
|       | [🚀 Presentation](https://docs.google.com/presentation/u/3/d/1CHY0SdpJt2MNgnVnpXVlEMSiE0AReCzC/edit?usp=drive_web&ouid=118344627946431951468&rtpof=true) |                                                                                                                                                          |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Day 4 | Collect, analyze, and present infectious disease data                                                                                                    |                                                                                                                                                          |
|       |                                                                                                                                                          |                                                                                                                                                          |
|       | [🚀 Presentation](https://docs.google.com/presentation/u/3/d/1wlKDuIurW89cNYu4pEgTfFqGE3GtcdZE/edit?usp=drive_web&ouid=118344627946431951468&rtpof=true) |                                                                                                                                                          |
+-------+----------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
