---
title: ""
sidebar: training
---

**Welcome to the SWAPER!**

To better support new team members in quickly understanding their roles and responsibilities, our department has developed a series of foundational training materials tailored to the specific functions of each team.

Our department consists of two key teams:

-   **Surveillance and Early Warning Team:** Focused on epidemiological surveillance and outbreak forecasting, this team requires a solid understanding of epidemiology as well as proficiency in R programming for data analysis and modeling.

-   **Preparedness and Emergency Response Team:** Responsible for ensuring rapid preparedness and effective response to public health emergencies, this team focuses on planning, coordination, and operational readiness during outbreaks.

These training modules aim to equip our new colleagues with essential knowledge and practical skills, ensuring a smooth integration into their respective roles while maintaining the high standards of our department’s work.

This page provides key documents and reference materials that support the SWAPER Department’s work in areas such as infectious disease modelling, health surveillance, epidemic risk assessment, and the effective coordination of public health emergency operations through established systems and frameworks.

We welcome you to explore the content and hope it supports you in building a strong foundation for your professional journey with us.

Let’s begin this important journey. 🌍💪
