---
title: ""
format: 
  dashboard:
    scrolling: true
    orientation: columns
    theme: custom.scss
---

```{r}
#| context: setup
library(plotly)
library(bslib)
library(bsicons)
library(summarywidget)
library(plotly)
source("sources_threshold.R")
source("sources_characteristics.R")
```

# Dengue fever 

## {.tabset}

### Thành phố 

#### Row {height=150px}

```{r}
#| width: 25%
sxh1
```

```{r}
#| width: 25%
sxh2
```

```{r}
#| width: 25%
sxh3
```

```{r}
#| width: 25%
sxh4
```

#### Row {height=600px}

```{r}
#| width: 70%
#| title: "Xu hướng dịch sốt xuất huyết"
#| fig-cap: "Các năm lịch sử: 2016,2017,2018,2020,2023"
#| fig-cap-location: top
sxh_interactive
```

```{r}
#| width: 30%
table_sxh
```

### Phường/Xã 

#### Row {height=500px}

```{r}
#| width: 65%
#| title: "Diễn tiến sốt xuất huyết tại 168 Phường/Xã"
px_sxh
```

```{r}
#| width: 35%
#| title: "Số ca sốt xuất huyết tại 168 Phường/Xã"
map_sxh
```

# Hand-Foot-Mouth Disease 

## {.tabset}

### Thành phố 

#### Row {height=150px}

```{r}
#| width: 25%
tcm1
```

```{r}
#| width: 25%
tcm2
```

```{r}
#| width: 25%
tcm3
```

```{r}
#| width: 25%
tcm4
```

#### Row {height=600px}

```{r}
#| width: 70%
#| title: "Xu hướng dịch tay chân miệng"
#| fig-cap: "Các năm lịch sử: 2017,2019,2020,2022,2024"
#| fig-cap-location: top
tcm_interactive
```

```{r}
#| width: 30%
table_tcm
```

### Phường/Xã 

#### Row {height=500px}

```{r}
#| width: 65%
#| title: "Diễn tiến sốt xuất huyết tại 168 Phường/Xã"
px_tcm
```

```{r}
#| width: 35%
#| title: "Số ca sốt xuất huyết tại 168 Phường/Xã"
map_tcm
```

