---
title: "Public Health Emergency Operations Centre"
sidebar: training
---

+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Day 2     | Overview of Public Health Emergency Operations Centre (PHEOC)                                                                                                                    | What is a Public Health Emergency Operations Centre                                       |
|           |                                                                                                                                                                                  |                                                                                           |
|           | [🚀 Presentation](https://www.canva.com/design/DAGe3gBWUIE/8uF9gSWxNpJjekoABS2hAw/edit?utm_content=DAGe3gBWUIE&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) | The PHEOC system and its modes of Operations                                              |
|           |                                                                                                                                                                                  |                                                                                           |
|           |                                                                                                                                                                                  | Core Functions and Structure                                                              |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Day 3     | Public Health Emergency Operations Centre at Ho Chi Minh City (PHEOC HCMC)                                                                                                       | Current Status of the City’s Disease Control Steering Committee Operations                |
|           |                                                                                                                                                                                  |                                                                                           |
|           | [🚀 Presentation](https://www.canva.com/design/DAGfC9XXN88/U4lnyroX_UxXibftZ6z3Ng/edit?utm_content=DAGfC9XXN88&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) | Organizational Structure of Public Health Emergency Management (PHEM) in Ho Chi Minh City |
|           |                                                                                                                                                                                  |                                                                                           |
|           |                                                                                                                                                                                  | Introduction to Ho Chi Minh City's PHEOC                                                  |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Day 4     | PHEOC Watch Mode                                                                                                                                                                 | Overview of Watch Level                                                                   |
|           |                                                                                                                                                                                  |                                                                                           |
|           | [🚀 Presentation](https://www.canva.com/design/DAGf-_JdNRc/UrPnQ0d-w26Fyih_RcTBEg/edit)                                                                                          | Core Activities                                                                           |
|           |                                                                                                                                                                                  |                                                                                           |
|           |                                                                                                                                                                                  | Key Outputs and Products                                                                  |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Day 5     | PHEOC Alert Mode                                                                                                                                                                 | Overview of Alert Level                                                                   |
|           |                                                                                                                                                                                  |                                                                                           |
|           | [🚀 Presentation](https://www.canva.com/design/DAGf_Ek3kjk/Qw036QkexCk1wZF306jNrQ/edit)                                                                                          | Core Activities                                                                           |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Day 6     | Overview of Rapid Response Team                                                                                                                                                  | Characteristics and operations                                                            |
|           |                                                                                                                                                                                  |                                                                                           |
|           | [🚀 Presentation](https://www.canva.com/design/DAGeridE8xg/5p1dXLVoerKF3qA-I0gW-g/edit?utm_content=DAGeridE8xg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) | Composition                                                                               |
|           |                                                                                                                                                                                  |                                                                                           |
|           |                                                                                                                                                                                  | Roles and responsibilities                                                                |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Day 6     | Rapid Response Team Management                                                                                                                                                   | Managers' responsibilities                                                                |
|           |                                                                                                                                                                                  |                                                                                           |
|           | [🚀 Presentation](https://www.canva.com/design/DAGhgWl3c5E/rMNQb1GzXrww9Sl4yAnROw/edit)                                                                                          | RRT in non-emergency phase                                                                |
|           |                                                                                                                                                                                  |                                                                                           |
|           |                                                                                                                                                                                  | RRT in emergency phase                                                                    |
|           |                                                                                                                                                                                  |                                                                                           |
|           |                                                                                                                                                                                  | Monitoring, supervision, and performance evaluation                                       |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Day 7     | PHEOC Response Mode                                                                                                                                                              | Overview of Response Level                                                                |
|           |                                                                                                                                                                                  |                                                                                           |
|           | [🚀 Presentation](https://www.canva.com/design/DAGf_PBfD6Y/p7VNHIpzTo5laq25hhnE0A/edit)                                                                                          | Incident Management System (IMS)                                                          |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Day 8     | PHEOC Deactivation and Recovery Mode                                                                                                                                             | Overview of Deactivation Level                                                            |
|           |                                                                                                                                                                                  |                                                                                           |
|           | [🚀 Presentation](https://www.canva.com/design/DAGf_Fajkco/T7RhkBngS6MPOn7pUOUpFQ/edit)                                                                                          | Overview of Recovery Level                                                                |
+-----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------+
